### ISSUE TITLE
Support fields for JDBC writer as nested list by YAML properties loader

### ISSUE THREAD

**Issue by pmwmedia** [Git5000/tinylog_extra_stuff#2]
The YAML properties loader can handle properties on the first level as nested objects, but not on further levels. Therefore, defining the fields for JDBC writers isn't such intuitiv.

Current format:

```yaml
writer:
   type: jdbc
   url: "jdbc:mysql://localhost:3306/example"
   table: LOG_ENTRIES
   field.TIMESTAMP: date
   field.LEVEL: level
   field.MESSAGE: "{class}.{method}() {message}"
```

Suggested format:

```yaml
writer:
   type: jdbc
   url: "jdbc:mysql://localhost:3306/example"
   table: LOG_ENTRIES
   field:
      TIMESTAMP: date
      LEVEL: level
      MESSAGE: "{class}.{method}() {message}"
```

Unfortunately, the current name for the field property is "field", but the plural "fields" would be better. In tinylog 3, I will rename this field to plural form. However, I'm not sure how to handle it in tinylog 2. Support both "field" and "fields"!?
